# Generated by Django 4.2.24 on 2025-09-26 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_category_options_alter_status_options_and_more'),
    ]

    operations = [
    ]
